name: $bog_selection_demo

permissions: write-all

on:
    workflow_dispatch:
    push:
    pull_request:

concurrency:
    group: deploy-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: hyoo-ru/mam_build@master2
              with:
                  package: "bog/selection"
                  modules: "demo"

            - uses: hyoo-ru/gh-deploy@v4.4.1
              if: github.ref == 'refs/heads/main'
              with:
                  folder: "bog/selection/demo/-"
